version: '3.8'

services:

  redis:
    image: redis:latest
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movierecommendation
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  neo4j:
    image: neo4j:latest
    container_name: neo4j-container
    restart: always
    environment:
      NEO4J_AUTH: neo4j/${NEO4J_PASSWORD}
      NEO4J_dbms_default__database: movierecommendation
    ports:
      - "7687:7687"  # Bolt protocol
      - "7474:7474"  # HTTP
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_conf:/conf
      - neo4j_plugins:/plugins

  movierecommendation:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movierecommendation
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - neo4j
      - mysql
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

      SPRING_NEO4J_URI: bolt://neo4j:7687
      SPRING_NEO4J_AUTHENTICATION_USERNAME: neo4j
      SPRING_NEO4J_AUTHENTICATION_PASSWORD: ${NEO4J_PASSWORD}
      SPRING_NEO4J_DATABASE: movierecommendation

      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/movierecommendation
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}

volumes:
  redis_data:
  mysql_data:
  neo4j_data:
  neo4j_logs:
  neo4j_conf:
  neo4j_plugins: