spring:
  profiles:
    active: prod

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH:/careergraph/api/v1}

logging:
  level:
    org.neo4j.driver: DEBUG
    org.springframework.data.neo4j: DEBUG
    org.springframework.transaction: DEBUG

jwt:
  signer-key: ${JWT_SIGNER_KEY:uT+Q3VZKCE+yNxmPoB0SH7qqDB8EGtBQY/F1GK2shIRKMZasRvvvyI5T/5y/FDX+}
  valid-duration: ${JWT_VALID_DURATION:3600}
  refreshable-duration: ${JWT_REFRESHABLE_DURATION:36000}

google:
  oauth:
    client-id: ${GOOGLE_OAUTH_CLIENT_ID:}
    client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET:}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
  packages-to-scan: com.hcmute.careergraph.controller
  paths-to-match: /api/**

swagger:
  username: ${SWAGGER_USERNAME:}
  password: ${SWAGGER_PASSWORD:}

support:
  email: ${SUPPORT_EMAIL:}

mail:
  host: ${MAIL_HOST:smtp.gmail.com}
  port: ${MAIL_PORT:587}
  username: ${MAIL_USERNAME:}
  password: ${MAIL_PASSWORD:}
  transport-protocol: ${MAIL_TRANSPORT_PROTOCOL:smtp}
  smtp-auth: ${MAIL_SMTP_AUTH:true}
  starttls-enable: ${MAIL_STARTTLS_ENABLE:true}
  debug: ${MAIL_DEBUG:false}

---

spring:
  config:
    activate:
      on-profile: dev
    import: optional:file:.env.dev[.properties]

---

spring:
  config:
    activate:
      on-profile: prod
    import: optional:file:.env.prod[.properties]
