spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/careergraph}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000  # 10m
      max-lifetime: 1800000 # 30m
      auto-commit: true
      data-source-properties:
        TimeZone: Asia/Ho_Chi_Minh


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
    properties:
      hibernate.jdbc.time_zone: UTC

  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}
    timeout: 2000ms
    database: 0
    password: ${SPRING_REDIS_PASSWORD:}
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
      shutdown-timeout: 100ms
  servlet:
    multipart:
      max-file-size: 5MB        # Giới hạn cho mỗi file
      max-request-size: 10MB

integration:
  s3:
    endpoint: ${INTEGRATION_S3_ENDPOINT:}
    accessKey: ${INTEGRATION_S3_ACCESS_KEY:}
    secretKey: ${INTEGRATION_S3_SECRET_KEY:}
    bucket: ${INTEGRATION_S3_BUCKET:}
    region: ${INTEGRATION_S3_REGION:}

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME:}
  api_key: ${CLOUDINARY_API_KEY:}
  api_secret: ${CLOUDINARY_API_SECRET:}