spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/careergraph
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000  # 10m
      max-lifetime: 1800000 # 30m
      auto-commit: true
      data-source-properties:
        TimeZone: Asia/Ho_Chi_Minh


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
    properties:
      hibernate.jdbc.time_zone: UTC

  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    database: 0
    password:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
      shutdown-timeout: 100ms
  servlet:
    multipart:
      max-file-size: 5MB        # Giới hạn cho mỗi file
      max-request-size: 10MB

integration:
  s3:
    endpoint: ${INTEGRATION_S3_ENDPOINT:https://s3.us-east-005.backblazeb2.com}
    accessKey: ${INTEGRATION_S3_ACCESS_KEY:0051ab9557af4e50000000001}
    secretKey: ${INTEGRATION_S3_SECRET_KEY:K005MflAlezZQmpSPEev9LHpTYvN0vU}
    bucket: ${INTEGRATION_S3_BUCKET:careergraph-files}
    region: ${INTEGRATION_S3_REGION:us-east-005}