spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/careergraph
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000  # 10m
      max-lifetime: 1800000 # 30m
      auto-commit: true


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true

  # Neo4j
  # neo4j:
  #   database: careergraph
  #   uri: bolt://localhost:7687
  #   authentication:
  #     username: neo4j
  #     password: Congquy2004@
  #   pool:
  #     max-connection-pool-size: 16
  #     idle-time-before-connection-test: 10s
  #     max-connection-lifetime: 1h

  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    database: 0
    password:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
      shutdown-timeout: 100ms

integration:  # When deploy -> Update into application.yml from docker-compose
  minio:
    url: http://localhost:9000
    accessKey: minioadmin
    secretKey: minioadmin
    bucket: careergraph