server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH:/careergraph/api/v1}

spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

logging:
  level:
    org.neo4j.driver: DEBUG
    org.springframework.data.neo4j: DEBUG
    org.springframework.transaction: DEBUG

jwt:
  signer-key: ${JWT_SIGNER_KEY:}
  valid-duration: ${JWT_VALID_DURATION:3600}
  refreshable-duration: ${JWT_REFRESHABLE_DURATION:36000}

google:
  oauth:
    client-id: ${GOOGLE_OAUTH_CLIENT_ID:}
    client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET:}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
  packages-to-scan: com.hcmute.careergraph.controller
  paths-to-match: /api/**

swagger:
  username: ${SWAGGER_USERNAME:}
  password: ${SWAGGER_PASSWORD:}

support:
  email: ${SUPPORT_EMAIL:}
