server:
  port: 8888
  servlet:
    context-path: careergraph/api/v1

spring:
  neo4j:
    database: movierecommendation
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: Congquy2004@
    pool:
      max-connection-pool-size: 16
      idle-time-before-connection-test: 10s
      max-connection-lifetime: 1h

  datasource:
    url: jdbc:mysql://localhost:3306/movierecommendation?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

logging:
  level:
    org.neo4j.driver: DEBUG
    org.springframework.data.neo4j: DEBUG
    org.springframework.transaction: DEBUG

jwt:
  signer-key: uT+Q3VZKCE+yNxmPoB0SH7qqDB8EGtBQY/F1GK2shIRKMZasRvvvyI5T/5y/FDX+
  valid-duration: 3600
  refreshable-duration: 36000